# This is a basic workflow to help you get started with Actions

name: Linux Unit Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO to fetch libraries for Bluepill
      run: platformio -d ${{ github.workspace }}/c6021light -e bluepill lib install

    # Runs a single command using the runners shell
    - uses: lukka/run-cmake@v2.5
      with:
        cmakeGenerator: UnixMakefiles
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeListsTxtPath: ${{ github.workspace }}/c6021light/CMakeLists.txt
        cmakeBuildType: Release
        buildDirectory: ${{ runner.temp }}/c6021light/build
        buildWithCMake: true

    # Actual testing happening
    - name: Run Unittest
      run: ${{ runner.temp }}/c6021light/build/c6021lightTest
