# This is a basic workflow to help you get started with Actions

name: Windows Unit Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        cache: 'pip'
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run PlatformIO to fetch libraries for Bluepill
      run: |
        cd ${{ github.workspace }}/c6021light
        platformio pkg install -e bluepill

    # Runs a single command using the runners shell
    - uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: ${{ github.workspace }}/c6021light/CMakeLists.txt
        configurePreset: "Windows"
        buildPreset: "Windows"

    - name: Examine Output
      run: dir ${{ github.workspace }}\..\c6021light-build-windows\

    # Actual testing happening
    - name: Run Unittest
      run: ${{ github.workspace }}\..\c6021light-build-windows\Debug\c6021lightTest.exe
